---
- hosts: all
  tasks:
  - name: Get number of cpus of each host
    shell: "nproc --all"
    register: host_cpus

- hosts: coordinator
  gather_facts: yes
  vars:
    exec_dir: "{{ execution_dir | default(ansible_env.HOME) }}"
  tasks:

  - name: Remove hosts file
    file:
      path: "{{ exec_dir }}/hosts"
      state: absent


  - name: Create hosts file
    file:
      path: "{{ exec_dir }}/hosts"
      state: touch

  - name: "Add Ansible inventory mappings to {{ exec_dir }}/hosts"
    blockinfile:
      marker: ""
      path: "{{ dest }}"
      block: |
        {% for host in groups['all'] %}
        {{ hostvars[host].ansible_host }} slots={{ hostvars[host].host_cpus.stdout }}
        {% endfor %}
