

---
- hosts: coordinator
  gather_facts: yes  
  become: no
  tasks:
#Besides executing the script, it will properly create the paramount(both .log and .err files) and the meta
# info file which contains the semantics/categorization of this execution (for data analysis purposes)

  - name: Deleting the data from the volume
    block:

    - name: Deleting the mpc directory
      file:
        state: absent
        path: "{{ cluster_folder }}/"
    when:  remove_data_from_sfs|bool

- hosts: all
  gather_facts: yes
  become: no
  tasks:
#Besides executing the script, it will properly create the paramount(both .log and .err files) and the meta
# info file which contains the semantics/categorization of this execution (for data analysis purposes)

  - name: Unmouting the volume
    include: ../../ec2-efs/tasks/unmount.yml
    vars:
      mount_point: cluster_folder






#