type-a:
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: t2.micro
    image_id: ami-07d0cf3af28718ef8
    security_group: otavio-sg
       
type-b:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    flavor: t2.medium
    image_id: ami-07d0cf3af28718ef8
    boot_disk_size: 10
    # image_userdata: 
    # boot_disk_device: /dev/sda1
    # boot_disk_iops: io1
    # boot_disk_type: gp2
    # placement_group: XXX
    
paramount-t2.medium:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: t2.medium
    
i-c5.large-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.large
    price: 1.0
    timeout: 600
    
i-c5n.large-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5n.large
    price: 1.0
    timeout: 600

i-m5n.large-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.large
    price: 1.0
    timeout: 600

i-r5.large-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.large
    price: 1.0
    timeout: 600
    
i-m5dn.large-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.large
    price: 1.0
    timeout: 600

i-c5.xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.xlarge
    price: 1.0
    timeout: 600

i-c5n.xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5n.xlarge
    price: 1.0
    timeout: 600

i-m5n.xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.xlarge
    price: 1.0
    timeout: 600

i-r5.xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.xlarge
    price: 1.0
    timeout: 600

i-m5dn.xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.xlarge
    price: 1.0
    timeout: 600
    
i-m5dn.xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.xlarge
    price: 1.0
    timeout: 600

i-c5.2xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.2xlarge
    price: 1.0
    timeout: 600
    
i-c5n.2xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5n.2xlarge
    price: 1.0
    timeout: 600

i-m5n.2xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.2xlarge
    price: 1.0
    timeout: 600
   
i-r5.2xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.2xlarge
    price: 1.0
    timeout: 600
    
i-m5dn.2xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.2xlarge
    price: 1.0
    timeout: 600
    
i-c5.4xlarge:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.4xlarge
    price: 1.0
    timeout: 600
    
i-c5n.4xlarge:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.4xlarge
    price: 1.0
    timeout: 600

i-m5n.4xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.4xlarge
    price: 1.0
    timeout: 600

i-r5.4xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.4xlarge
    price: 1.0
    timeout: 600

i-m5dn.4xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.4xlarge
    price: 1.0
    timeout: 600

i-c5.9xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.9xlarge
    price: 1.0
    timeout: 600

i-m5n.8xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.8xlarge
    price: 1.0
    timeout: 600

i-c5n.9xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5n.9xlarge
    price: 1.0
    timeout: 600

i-r5.8xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.8xlarge
    price: 1.0
    timeout: 600

i-c5.12xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.12xlarge
    price: 1.0
    timeout: 600

i-m5dn.8xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.8xlarge
    price: 1.0
    timeout: 600

i-m5n.12xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.12xlarge
    price: 1.0
    timeout: 600

i-r5.12xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.12xlarge
    price: 1.0
    timeout: 600

i-c5.18xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.18xlarge
    price: 1.0
    timeout: 600

i-m5dn.12xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.12xlarge
    price: 1.0
    timeout: 600

i-m5n.16xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.16xlarge
    price: 1.0
    timeout: 600

i-c5n.18xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5n.18xlarge
    price: 1.0
    timeout: 600

i-r5.16xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.16xlarge
    price: 1.0
    timeout: 600

i-c5.24xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: c5.24xlarge
    price: 1.0
    timeout: 600

i-m5dn.16xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.16xlarge
    price: 1.0
    timeout: 600

i-m5n.24xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5n.24xlarge
    price: 1.0
    timeout: 600

i-r5.24xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: r5.24xlarge
    price: 1.0
    timeout: 600

i-m5dn.24xlarge-spot:
    provider: aws-config-us-east-1
    login: login-ubuntu-b
    image_id: ami-0cbe953fb7b8fff02
    flavor: m5dn.24xlarge
    price: 1.0
    timeout: 600

